site_name: Paul Documentation and Information
site_description: Documentation and information about Paul, a privacy-focused AI assistant.
site_author: Ronen Lazowski
site_url: https://lazowski.me
use_directory_urls: true

theme:
  name: material

nav:
  - Home: index.md
  - Privacy Policy: PRIVACY.md
  - Terms of Service: TERMS.md
  - Required Intents: INTENTS.md

extra_files:
  - CNAME

repo_url: https://github.com/ronenlazowski/paul
